name: "Upload artifact"

description: "Upload artifact"

inputs:
  artifact_name:
    required: true
    type: string
  artifact_path:
    required: true
    type: string
  basepath:
    required: false
    type: boolean
    default: ""

runs:
  using: "composite"
  steps:
    - name: "Prepare artifact"
      shell: bash
      run: |
        mkdir -p ./artifact
        cp -r ${{ inputs.artifact_path }} ./artifact/${{ inputs.basepath }}

    - name: "Upload artifact"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ./artifact
        if-no-files-found: error
        include-hidden-files: true
        retention-days: 1
