name: "Deploy"

on:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  call-deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      AWS_LAMBDA_FUNCTION_NAME: ${{ vars.AWS_LAMBDA_FUNCTION_NAME }}
      AWS_LAMBDA_LAYER_NAME_APP: "generate-pdf-app"
      AWS_LAMBDA_LAYER_NAME_FUNCTION: "generate-pdf-function"
      AWS_LAMBDA_LAYER_NAME_FONTS: "generate-pdf-fonts"
      AWS_LAMBDA_LAYER_NAME_CHROMIUM: "generate-pdf-chromium"
      env: "production"
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
