name: "Reusable deploy"

on:
  workflow_call:
    inputs:
      AWS_LAMBDA_FUNCTION_NAME:
        type: string
        required: true
      AWS_LAMBDA_LAYER_NAME_APP:
        type: string
        required: true
      AWS_LAMBDA_LAYER_NAME_FUNCTION:
        type: string
        required: true
      AWS_LAMBDA_LAYER_NAME_FONTS:
        type: string
        required: true
      AWS_LAMBDA_LAYER_NAME_CHROMIUM:
        type: string
        required: true
      env:
        type: string
        required: true
    secrets:
      AWS_ACCOUNT_ID:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  call-deploy-layer-app:
    uses: ./.github/workflows/reusable-deploy-layer-app.yml
    with:
      AWS_LAMBDA_LAYERS_NAME: "generate-pdf-app"
      env: 
      artifact_name: "generate-pdf-app--production"
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  call-deploy-layer-fonts:
    uses: ./.github/workflows/reusable-deploy-layer-fonts.yml
    with:
      AWS_LAMBDA_LAYERS_NAME: "generate-pdf-fonts"
      artifact_name: "generate-pdf-fonts--production"
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  call-update-function-configuration:
    uses: ./.github/workflows/reusable-update-function-configuration.yml
    with:
      AWS_LAMBDA_FUNCTION_NAME: ${{ inputs.AWS_LAMBDA_FUNCTION_NAME }}
      AWS_LAMBDA_LAYER_NAME_APP: ${{ inputs.AWS_LAMBDA_LAYER_NAME_APP }}
      AWS_LAMBDA_LAYER_NAME_FUNCTION: ${{ inputs.AWS_LAMBDA_LAYER_NAME_FUNCTION }}
      AWS_LAMBDA_LAYER_NAME_FONTS: ${{ inputs.AWS_LAMBDA_LAYER_NAME_FONTS }}
      AWS_LAMBDA_LAYER_NAME_CHROMIUM: ${{ inputs.AWS_LAMBDA_LAYER_NAME_CHROMIUM }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
