name: "Reusable deploy function Lambda Layer"

on:
  workflow_call:
    inputs:
      AWS_LAMBDA_LAYERS_NAME:
        type: string
        required: true
      env:
        type: string
        required: true
      artifact_name_function_code:
        type: string
        required: true
      artifact_name_node_modules:
        type: string
        required: true
    secrets:
      AWS_ACCOUNT_ID:
        required: true

permissions:
  id-token: write
  contents: read

env:
  zip_file_name: "Layer.zip"

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.filter.outputs.targets }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            targets:
              - "packages/app/**"
              - "packages/function/**"
              - ".github/actions/upload-artifact/action.yml"
              - ".github/actions/get-lambda-layer-arn-suffix/action.yml"
              - ".github/workflows/reusable-deploy-layer-function.yml"
              - ".github/workflows/reusable-publish-layer.yml"
              - ".github/workflows/reusable-update-function-configuration.yml"

  build-function:
    needs: changes
    if: ${{ needs.changes.outputs.exists == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Node.js for app"
        uses: actions/setup-node@v4
        with:
          node-version: "18.16.1"
          cache: "npm"
          cache-dependency-path: "packages/app/package-lock.json"

      - name: "Install dependencies for app"
        run: npm ci --only=prod
        working-directory: "packages/app"

      - name: "Build app"
        run: npm run build
        working-directory: "packages/app"

      - name: "Setup Node.js for function"
        uses: actions/setup-node@v4
        with:
          node-version: "18.16.1"
          cache: "npm"
          cache-dependency-path: "packages/function/package-lock.json"

      - name: "Install dependencies for function"
        run: npm ci --only=prod
        working-directory: "packages/function"

      - name: "Prepare node_modules"
        run: |
          mkdir -p ./packages/function/dependencies/nodejs
          cp -r ./packages/function/node_modules ./packages/function/dependencies/nodejs

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name_node_modules }}
          path: ./packages/function/dependencies
          if-no-files-found: error
          include-hidden-files: true
          retention-days: 1

      - name: "Prepare function code"
        run: |
          mkdir -p packages/function/dist
          mkdir packages/function/dist/src
          mkdir packages/function/dist/.output
          cp -r packages/function/index.mjs packages/function/dist
          cp -r packages/function/src/ packages/function/dist
          cp -r packages/app/.output/ packages/function/dist

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name_function_code }}
          path: ./packages/function/dist
          if-no-files-found: error
          include-hidden-files: true
          retention-days: 1

  call-publish-layer:
    uses: ./.github/workflows/reusable-publish-layer.yml
    needs: build-function
    with:
      AWS_LAMBDA_LAYERS_NAME: ${{ inputs.AWS_LAMBDA_LAYERS_NAME }}
      artifact_name: ${{ inputs.artifact_name_node_modules }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
