name: "Reusable deploy fonts Lambda Layer"

on:
  workflow_call:
    inputs:
      s3_bucket_name:
        type: string
        required: true
      lambda_layer_name:
        type: string
        required: true
      artifact_name:
        type: string
        required: true
    secrets:
      AWS_ACCOUNT_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.filter.outputs.targets }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            targets:
              - "packages/function/fonts/**"
              - ".github/actions/get-lambda-layer-arn-suffix/action.yml"
              - ".github/workflows/reusable-deploy.yml"
              - ".github/workflows/reusable-deploy-layer-fonts.yml"
              - ".github/workflows/reusable-publish-layer.yml"
              - ".github/workflows/reusable-update-function-configuration.yml"

  build-fonts:
    needs: changes
    if: ${{ needs.changes.outputs.exists == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Prepare"
        run: |
          mkdir -p ./packages/function/dist/fonts
          cp -r ./packages/function/fonts ./packages/function/dist

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ./packages/function/dist
          if-no-files-found: error
          include-hidden-files: true
          retention-days: 1

  call-publish-layer-version:
    uses: ./.github/workflows/reusable-publish-layer.yml
    needs: build-fonts
    with:
      artifact_name: ${{ inputs.artifact_name }}
      s3_bucket_name: ${{ inputs.s3_bucket_name }}
      s3_file_path: "fonts.zip"
      lambda_layer_name: ${{ inputs.lambda_layer_name }}
      lambda_layer_description: "Fonts for generate-pdf Lambda function"
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
