name: "Reusable tests"

on:
  workflow_call:
    secrets:
      AWS_ACCOUNT_ID:
        required: true

env:
  AWS_ROLE_ARN: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ROLE_NAME }}"

permissions:
  id-token: write
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      - name: "Install dependencies for pdf-generator"
        run: npm ci
        working-directory: "packages/function"

      - name: "Typecheck for pdf-generator"
        run: npm run typecheck
        working-directory: "packages/function"

      - name: "Lint & Format for pdf-generator"
        run: npm run check:ci
        working-directory: "packages/function"

      - name: "Unit tests for pdf-generator"
        run: npm run test
        working-directory: "packages/function"
