name: "Reusable deploy"

on:
  workflow_call:
    inputs:
      lambda_function_name:
        type: string
        required: true 
      s3_bucket_name:
        type: string
        required: true
      lambda_layer_name_node_modules:
        type: string
        required: true
      lambda_layer_name_fonts:
        type: string
        required: true
      lambda_layer_name_chromium:
        type: string
        required: true
      s3_file_path_function_code:
        type: string
        required: true
      env:
        type: string
        required: true
    secrets:
      AWS_ACCOUNT_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  call-deploy-layer-function:
    uses: ./.github/workflows/reusable-deploy-layer-function.yml
    with:
      env: ${{ inputs.env }}
      artifact_name_function_code: "generate-pdf-function-code--${{ inputs.env }}"
      artifact_name_node_modules: "generate-pdf-node-modules--${{ inputs.env }}"
      s3_bucket_name: ${{ inputs.s3_bucket_name }}
      s3_file_path_function_code: ${{ inputs.s3_file_path_function_code }}
      lambda_layer_name_node_modules: ${{ inputs.lambda_layer_name_node_modules }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  call-deploy-layer-fonts:
    uses: ./.github/workflows/reusable-deploy-layer-fonts.yml
    with:
      s3_bucket_name: ${{ inputs.s3_bucket_name }}
      lambda_layer_name: ${{ inputs.lambda_layer_name_fonts }}
      artifact_name: "generate-pdf-fonts--${{ inputs.env }}"
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  call-deploy-layer-chromium:
    uses: ./.github/workflows/reusable-deploy-layer-chromium.yml
    with:
      lambda_layer_name: ${{ inputs.lambda_layer_name_chromium }}
      s3_bucket_name: ${{ inputs.s3_bucket_name }}
      artifact_name: "generate-pdf-chromium--${{ inputs.env }}"
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  call-update-function-configuration:
    uses: ./.github/workflows/reusable-update-function-configuration.yml
    needs:
      [
        call-deploy-layer-function,
        call-deploy-layer-fonts,
        call-deploy-layer-chromium,
      ]
    with:
      lambda_function_name: ${{ inputs.lambda_function_name }}
      lambda_layer_name_node_modules: ${{ inputs.lambda_layer_name_node_modules }}
      lambda_layer_name_fonts: ${{ inputs.lambda_layer_name_fonts }}
      lambda_layer_name_chromium: ${{ inputs.lambda_layer_name_chromium }}
      s3_bucket_name: ${{ inputs.s3_bucket_name }}
      s3_file_path_function_code: ${{ inputs.s3_file_path_function_code }}
      artifact_name_function_code: "generate-pdf-function-code--${{ inputs.env }}"
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
